#!/usr/bin/env python3
"""Stage 2, Backend B: build the SKY130 OpenRAM/OpenROM parameter macros.

    scripts/gen_weight_rom_openram.py

It consumes the SAME canonical parameter images as the portable backend
(src/model2rtl/param_image.py) -- there is exactly one packing implementation
in this project -- writes OpenROM input data files, invokes the ACTUAL
installed OpenROM compiler, verifies the produced files rather than trusting an
exit code, parses the DRC/LVS reports, and emits the fixed-interface wrapper

    rtl/mnist_mlp_params_openram.v

Nothing is claimed that was not produced.  Every macro's real outcome, including
the tool limitations that block a shape, is recorded in
build/openram/openram_build.json and reported verbatim.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from model2rtl import memif                                     # noqa: E402
from model2rtl.fabric import FabricConfig                       # noqa: E402
from model2rtl.param_image import (IMAGE_ORDER, ParamImage,     # noqa: E402
                                   build_images, default_dir, write_images)
from model2rtl.param_verilog import (emit_openram_backend,      # noqa: E402
                                     emit_selector, emit_top)
from model2rtl import storage as S                              # noqa: E402

OPENRAM_ROOT = "/home/rithwik/OpenRAM"
PDK_ROOT = "/home/rithwik/pdk"
BUILD = os.path.join(ROOT, "build", "openram")
ENV_SH = os.path.join(BUILD, "openram_env.sh")

#: words_per_row values that this installed OpenROM version can actually route
#: for each shape, established by the sweep recorded in the Stage-2 report.
#: words_per_row is an INTERNAL physical folding option: it changes the array
#: aspect ratio, never the logical depth, word width or bit packing.
WORDS_PER_ROW = {"weights_l1": 2, "weights_l2": 4}


def sha256_file(path: str) -> str:
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def openram_env() -> dict:
    env = dict(os.environ)
    env.update({
        "OPENRAM_ROOT": OPENRAM_ROOT,
        "OPENRAM_HOME": os.path.join(OPENRAM_ROOT, "compiler"),
        "OPENRAM_TECH": os.path.join(OPENRAM_ROOT, "technology"),
        "PDK_ROOT": PDK_ROOT,
        "PDKPATH": os.path.join(PDK_ROOT, "sky130A"),
        "PYTHONPATH": os.path.join(OPENRAM_ROOT, "compiler"),
        "PATH": "/home/rithwik/netgen-install/bin:"
                "/home/rithwik/klayout_cf/magic/bin:" + os.environ.get("PATH", ""),
    })
    return env


def write_rom_data(img: ParamImage, path: str) -> dict:
    """Write the OpenROM input file and prove it carries the canonical image.

    The file is the canonical rows, row 0 first, each row big-endian, written as
    one line of hex -- which is exactly the format OpenROM's hex reader expects.
    """
    if img.width % 4:
        raise ValueError("%s: width %d is not a whole number of hex digits"
                         % (img.name, img.width))
    text = "".join(img.hex_lines())
    with open(path, "w") as fh:
        fh.write(text)

    # independent read-back: decode the file the way OpenROM decodes it and
    # require the bit stream to equal the canonical image bit for bit
    raw = open(path).read().strip()
    bits = bin(int(raw, 16))[2:].zfill(len(raw) * 4)
    if bits != img.bit_string_msb_first():
        raise SystemExit("%s: ROM data file does not match the canonical image"
                         % img.name)
    return {
        "path": path,
        "sha256": sha256_file(path),
        "bits": len(bits),
        "canonical_image_sha256": img.sha256(),
        "bitstream_matches_canonical_image": True,
    }


def write_config(macro: str, img: ParamImage, wpr: int, outdir: str,
                 data_path: str, check_lvsdrc: bool) -> str:
    if img.width % 8:
        raise ValueError("byte granularity")
    cfg_path = os.path.join(outdir, macro + "_cfg.py")
    with open(cfg_path, "w") as fh:
        fh.write(f"""# GENERATED by scripts/gen_weight_rom_openram.py (model2rtl Stage 2)
# Logical shape requested: {img.depth} words x {img.width} bits ({img.name}).
# words_per_row is an internal physical folding choice only; the logical depth,
# word width and bit packing are unchanged.
word_size = {img.width // 8}
words_per_row = {wpr}
check_lvsdrc = {check_lvsdrc}
use_nix = False
rom_data = "{data_path}"
data_type = "hex"
output_name = "{macro}"
output_path = "{os.path.join(outdir, 'out')}/"
tech_name = "sky130"
nominal_corner_only = True
route_supplies = "ring"
""")
    return cfg_path


def parse_reports(outdir: str, macro: str, log_text: str) -> dict:
    """Parse the ACTUAL DRC/LVS outcome. An exit code proves nothing."""
    drc_errors = None
    m = re.search(r"DRC Errors\s+%s\s+(\d+)" % re.escape(macro), log_text)
    if m:
        drc_errors = int(m.group(1))
    elif re.search(r"DRC.*%s.*(passed|clean)" % re.escape(macro), log_text, re.I):
        drc_errors = 0
    lvs = "not run"
    if re.search(r"%s\s+LVS mismatch" % re.escape(macro), log_text):
        lvs = "MISMATCH"
    elif re.search(r"LVS.*(passed|clean)", log_text, re.I):
        lvs = "clean"
    reports = {}
    for pat in (".drc.report", ".lvs.report", ".ext.log"):
        for base in (outdir, os.path.join(outdir, "out")):
            p = os.path.join(base, macro + pat)
            if os.path.exists(p):
                reports[pat] = {"path": p, "size": os.path.getsize(p)}
    return {
        "drc_errors": drc_errors,
        "drc_status": ("clean" if drc_errors == 0 else
                       ("%d errors" % drc_errors) if drc_errors is not None
                       else "not run / not reported"),
        "lvs_status": lvs,
        "reports_found": reports,
        "fatal_lines": [l for l in log_text.splitlines()
                        if "FATAL" in l or l.startswith("ERROR")][:10],
    }


def build_macro(macro: str, img: ParamImage, check_lvsdrc: bool,
                timeout: int) -> dict:
    outdir = os.path.join(BUILD, macro)
    os.makedirs(outdir, exist_ok=True)
    result = {
        "macro": macro,
        "requested_depth": img.depth,
        "requested_width_bits": img.width,
        "canonical_image_sha256": img.sha256(),
    }

    if img.width % 8:
        result.update({
            "status": "BLOCKED",
            "blocked_reason":
                "OpenROM's word_size is expressed in BYTES (rom_config.py sets "
                "word_bits = word_size * 8), so a %d-bit word cannot be "
                "requested. Generating this macro would require changing the "
                "word width, which Stage 2 forbids without explicit approval."
                % img.width,
            "proposed_fix_not_implemented":
                "pad the word to %d bits (%d bytes) in the physical macro and "
                "slice it back in the wrapper" % (((img.width + 7) // 8) * 8,
                                                  (img.width + 7) // 8),
        })
        return result

    wpr = WORDS_PER_ROW[macro]
    data_path = os.path.join(outdir, macro + ".hex")
    result["rom_data"] = write_rom_data(img, data_path)
    result["words_per_row"] = wpr
    result["physical_rows"] = img.depth // wpr
    result["physical_cols"] = img.width * wpr

    def run(cfg_path):
        cmd = [os.path.join(OPENRAM_ROOT, ".venv", "bin", "python"),
               os.path.join(OPENRAM_ROOT, "rom_compiler.py"), "-d", cfg_path]
        t0 = time.time()
        try:
            p = subprocess.run(cmd, cwd=outdir, env=openram_env(),
                               capture_output=True, text=True, timeout=timeout)
            rc, out = p.returncode, p.stdout + p.stderr
        except subprocess.TimeoutExpired as e:
            rc, out = -1, "TIMEOUT after %d s\n%s" % (timeout, e.stdout or "")
        return rc, out, time.time() - t0

    # Pass 1 (optional): DRC/LVS probe.  In this environment a DRC failure makes
    # OpenRAM abort before it writes any view, so the probe is run separately
    # and its ONLY purpose is to record the real physical-verification outcome.
    if check_lvsdrc:
        probe_cfg = write_config(macro + "_drclvs", img, wpr, outdir,
                                 data_path, True)
        prc, pout, pelapsed = run(probe_cfg)
        with open(os.path.join(outdir, macro + "_drclvs.log"), "w") as fh:
            fh.write(pout)
        result["lvsdrc_probe"] = dict(
            parse_reports(outdir, macro + "_drclvs", pout),
            returncode=prc, elapsed_seconds=round(pelapsed, 1),
            log=os.path.relpath(os.path.join(outdir, macro + "_drclvs.log"), ROOT))
    else:
        result["lvsdrc_probe"] = {
            "drc_status": "not run",
            "lvs_status": "not run",
            "note": "physical verification not attempted for this macro",
        }

    # Pass 2: generate the macro views.
    cfg = write_config(macro, img, wpr, outdir, data_path, False)
    result["config"] = cfg
    rc, out, elapsed = run(cfg)

    logpath = os.path.join(outdir, macro + "_compile.log")
    with open(logpath, "w") as fh:
        fh.write(out)

    od = os.path.join(outdir, "out")
    views = {}
    for ext in ("gds", "sp", "lvs.sp", "lef", "v", "log", "py"):
        p = os.path.join(od, "%s.%s" % (macro, ext))
        if os.path.exists(p) and os.path.getsize(p) > 0:
            views[ext] = {"path": os.path.relpath(p, ROOT),
                          "bytes": os.path.getsize(p),
                          "sha256": sha256_file(p)}

    result.update({
        "returncode": rc,
        "elapsed_seconds": round(elapsed, 1),
        "compile_log": os.path.relpath(logpath, ROOT),
        "views_generated": sorted(views),
        "views": views,
        "physical_verification": result["lvsdrc_probe"],
    })
    required = ["gds", "sp", "v", "lef"]
    missing = [v for v in required if v not in views]
    result["missing_expected_views"] = missing
    result["status"] = "PASS" if (rc == 0 and not missing) else "FAIL"
    if rc != 0:
        result["failure_tail"] = out.strip().splitlines()[-6:]
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--macros", nargs="*", default=list(IMAGE_ORDER))
    ap.add_argument("--no-lvsdrc", action="store_true",
                    help="skip the DRC/LVS probe pass (views are still built)")
    ap.add_argument("--timeout", type=int, default=7200)
    ap.add_argument("--skip-build", action="store_true",
                    help="only re-emit the RTL from the recorded build results")
    args = ap.parse_args()

    cfg = FabricConfig()
    memif.verify_against_rtl(os.path.join(ROOT, "rtl", "mnist_mlp_fabric.v"), cfg)
    model = S.load_indices(S.default_paths(ROOT)["npz"])
    images = build_images(model, cfg)
    write_images(default_dir(ROOT), images)
    os.makedirs(BUILD, exist_ok=True)
    results_path = os.path.join(BUILD, "openram_build.json")

    results = {}
    if args.skip_build and os.path.exists(results_path):
        results = json.load(open(results_path))["macros"]
    else:
        for macro in args.macros:
            print("== OpenROM macro: %s ==" % macro)
            r = build_macro(macro, images[macro], not args.no_lvsdrc,
                            args.timeout)
            results[macro] = r
            print("   status=%s %s" % (r["status"],
                                       r.get("blocked_reason", "")[:70]))
            if r["status"] == "PASS":
                print("   views=%s  DRC=%s  LVS=%s  %.1fs"
                      % (r["views_generated"],
                         r["physical_verification"]["drc_status"],
                         r["physical_verification"]["lvs_status"],
                         r["elapsed_seconds"]))

    with open(results_path, "w") as fh:
        json.dump({"macros": results,
                   "openram_root": OPENRAM_ROOT,
                   "pdk_root": PDK_ROOT}, fh, indent=2, sort_keys=True)
        fh.write("\n")

    status = {m: ("physical macro generated (%s)"
                  % ", ".join(results[m]["views_generated"]))
              if results.get(m, {}).get("status") == "PASS"
              else "physical macro NOT generated: %s"
                   % results.get(m, {}).get("status", "not attempted")
              for m in IMAGE_ORDER}

    rtl = os.path.join(ROOT, "rtl")
    with open(os.path.join(rtl, "mnist_mlp_params_openram.v"), "w") as fh:
        fh.write(emit_openram_backend(images, cfg, macro_status=status))
    with open(os.path.join(rtl, "mnist_mlp_top.v"), "w") as fh:
        fh.write(emit_top(cfg))
    with open(os.path.join(rtl, "mnist_mlp_params_sel_portable.v"), "w") as fh:
        fh.write(emit_selector("mnist_mlp_params_portable", cfg))
    with open(os.path.join(rtl, "mnist_mlp_params_sel_openram.v"), "w") as fh:
        fh.write(emit_selector("mnist_mlp_params_openram", cfg))

    print("\nwrote rtl/mnist_mlp_params_openram.v, rtl/mnist_mlp_top.v and both "
          "selector files")
    print("build record: %s" % os.path.relpath(results_path, ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
