#!/usr/bin/env python3
"""Stage 5: run the available DRC/LVS on every final macro AND on a control.

The local physical-verification environment is already known to be unreliable:
in Stage 2 OpenRAM's OWN upstream reference macro failed with 830 DRC errors and
an LVS mismatch.  Stage 5 does not try to repair the environment.  It re-runs
the same control under identical settings, runs the same check on every Stage-5
macro, and reports both.

A macro is never called DRC-clean or LVS-clean on the strength of these runs:
physical GENERATION is reported separately from physical SIGNOFF.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import re
import shutil
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from model2rtl import openrom as O                              # noqa: E402
from model2rtl import phys_image as P                           # noqa: E402
from model2rtl import storage as S                              # noqa: E402
from model2rtl.fabric import FabricConfig                       # noqa: E402
from model2rtl.param_image import build_images                  # noqa: E402

BUILD = os.path.join(ROOT, "build", "stage5", "drclvs")
RECORD = os.path.join(ROOT, "build", "stage5", "stage5_drclvs.json")
MACRO_RECORD = os.path.join(ROOT, "build", "stage5",
                            "stage5_openrom_build.json")

#: OpenRAM's own reference ROM, byte for byte: the same 1 kbyte example data,
#: the same word_size and the same settings the upstream macro uses.  Nothing
#: in the OpenRAM tree is modified; only the output directory is redirected.
CONTROL_DATA = "/home/rithwik/OpenRAM/macros/rom_configs/example_1kbyte.bin"
CONTROL_NAME = "control_rom_1kbyte_upstream"


def _parse_drclvs(log: str, name: str) -> dict:
    drc = None
    m = re.search(r"DRC Errors\s+%s\s+(\d+)" % re.escape(name), log)
    if m:
        drc = int(m.group(1))
    tiles = re.findall(r"Cell (\S+) has (\d+) error tiles", log)
    lvs = "not reported"
    if re.search(r"%s\s+LVS mismatch" % re.escape(name), log):
        lvs = "MISMATCH"
    else:
        m2 = re.search(r"LVS Errors\s+%s\s+(\d+)" % re.escape(name), log)
        if m2:
            lvs = "clean" if int(m2.group(1)) == 0 else "%s errors" % m2.group(1)
        elif re.search(r"Circuits match uniquely", log):
            lvs = "clean"
        elif re.search(r"Netlists do not match", log):
            lvs = "MISMATCH"
    return {
        "drc_errors": drc,
        "drc_status": ("clean" if drc == 0 else "%d errors" % drc
                       if drc is not None else "not reported"),
        "drc_error_tiles": [{"cell": c, "tiles": int(t)} for c, t in tiles][:20],
        "lvs_status": lvs,
    }


def run_one(name: str, word_size_bytes: int, wpr, data_path: str,
            data_type: str, timeout: int) -> dict:
    outdir = os.path.join(BUILD, name)
    os.makedirs(os.path.join(outdir, "out"), exist_ok=True)
    cfg_path = os.path.join(outdir, name + "_cfg.py")
    wpr_line = "" if wpr is None else "words_per_row = %d\n" % wpr
    with open(cfg_path, "w") as fh:
        fh.write("""# GENERATED by model2rtl Stage 5: DRC/LVS pass.
word_size = %d
%scheck_lvsdrc = True
use_nix = False
rom_data = "%s"
data_type = "%s"
output_name = "%s"
output_path = "%s/"
tech_name = "sky130"
nominal_corner_only = True
route_supplies = "ring"
""" % (word_size_bytes, wpr_line, data_path, data_type, name,
       os.path.join(outdir, "out")))

    cmd = [os.path.join(O.OPENRAM_ROOT, ".venv", "bin", "python"),
           os.path.join(O.OPENRAM_ROOT, "rom_compiler.py"), "-d", cfg_path]
    t0 = time.time()
    try:
        p = subprocess.run(cmd, cwd=outdir, env=O.openram_env(),
                           stdin=subprocess.DEVNULL, capture_output=True,
                           text=True, timeout=timeout)
        rc, log = p.returncode, p.stdout + p.stderr
    except subprocess.TimeoutExpired as exc:
        rc, log = -1, "TIMEOUT after %d s\n%s" % (timeout, exc.stdout or "")
    elapsed = time.time() - t0
    logpath = os.path.join(outdir, name + "_drclvs.log")
    with open(logpath, "w") as fh:
        fh.write(log)

    out = _parse_drclvs(log, name)
    out.update({
        "macro": name,
        "returncode": rc,
        "elapsed_seconds": round(elapsed, 1),
        "log": os.path.relpath(logpath, ROOT),
        "config": os.path.relpath(cfg_path, ROOT),
        "reached_verification": ("DRC Errors" in log or "LVS" in log),
    })
    if not out["reached_verification"]:
        out["error_signature"] = O.error_signature(log)
    print("   %-28s DRC=%-12s LVS=%-10s rc=%d %.0fs"
          % (name, out["drc_status"], out["lvs_status"], rc, elapsed),
          flush=True)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--timeout", type=int, default=21600)
    ap.add_argument("--jobs", type=int, default=8)
    args = ap.parse_args()

    if not os.path.exists(MACRO_RECORD):
        print("FATAL: run scripts/gen_openrom_stage5.py first", file=sys.stderr)
        return 1
    macros = json.load(open(MACRO_RECORD))["macros"]

    cfg = FabricConfig()
    model = S.load_indices(S.default_paths(ROOT)["npz"])
    phys = P.build_physical_images(build_images(model, cfg))

    os.makedirs(BUILD, exist_ok=True)
    jobs = []
    # the control first, so it is never omitted
    jobs.append((CONTROL_NAME, 1, None, CONTROL_DATA, "bin"))
    for name in P.PHYS_ORDER:
        m = macros.get(name)
        if not m or not m.get("generated"):
            print("skipping %s: not generated" % name)
            continue
        data = os.path.join(ROOT, m["data_image"]["path"])
        jobs.append((name, phys[name].width // 8, m["words_per_row"], data,
                     "hex"))

    print("== DRC/LVS: %d runs (control + %d macros) =="
          % (len(jobs), len(jobs) - 1), flush=True)
    results = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futs = {pool.submit(run_one, n, ws, w, d, t, args.timeout): n
                for n, ws, w, d, t in jobs}
        for f in concurrent.futures.as_completed(futs):
            r = f.result()
            results[r["macro"]] = r

    control = results.get(CONTROL_NAME, {})
    trustworthy = (control.get("drc_errors") == 0
                   and control.get("lvs_status") == "clean")
    record = {
        "toolchain": O.toolchain_versions(),
        "control": control,
        "control_description":
            "OpenRAM's own upstream reference ROM (rom_configs/"
            "example_1kbyte.bin, word_size 1, the settings sky130_rom_1kbyte.py "
            "uses). Nothing in the OpenRAM tree was modified; only the output "
            "directory was redirected.",
        "control_is_clean": trustworthy,
        "macros": {k: v for k, v in results.items() if k != CONTROL_NAME},
        "signoff_status": ("VERIFIED" if trustworthy else "UNVERIFIED"),
        "signoff_reasoning":
            ("The upstream reference macro passes DRC and LVS here, so macro "
             "results are meaningful."
             if trustworthy else
             "The upstream reference macro itself fails in this environment, "
             "so no DRC or LVS result produced here is evidence about "
             "model2rtl's macros. Physical GENERATION is reported separately "
             "from physical SIGNOFF, and signoff is UNVERIFIED."),
    }
    tmp = RECORD + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(record, fh, indent=2, sort_keys=True)
        fh.write("\n")
    os.replace(tmp, RECORD)
    print("\ncontrol clean: %s -> physical signoff %s"
          % (trustworthy, record["signoff_status"]))
    print("wrote %s" % os.path.relpath(RECORD, ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
