"""Stage 5: a reusable driver for the installed OpenROM compiler.

Nothing here trusts an exit code.  Every run is judged by the artefacts it
actually produced, every macro's bit content is re-derived independently from
the generated SPICE netlist, and every measured area comes from the generated
GDS rather than from a log line.

The installed toolchain is used exactly as it is: OpenRAM stable at commit
b2b069ce119d1488cbe6883b2240bceb5c7ce29a with PDK_ROOT=/home/rithwik/pdk.
Stage 5 does not update, patch or fork it.
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple

OPENRAM_ROOT = "/home/rithwik/OpenRAM"
PDK_ROOT = "/home/rithwik/pdk"
KLAYOUT = os.path.expanduser("~/klayout_cf/klqt/klayout")

#: words_per_row is an INTERNAL physical folding choice.  It changes the array
#: aspect ratio only: never the logical depth, the word width or the bit
#: packing.  words_per_row = 1 is excluded because it crashes this OpenROM
#: revision (rom_address_control_array has no attribute local_insts).
DEFAULT_WPR_CANDIDATES = (4, 8, 2, 16)

VIEW_EXTS = ("gds", "sp", "lvs.sp", "lef", "v", "log", "py", "html")
REQUIRED_VIEWS = ("gds", "sp", "lvs.sp", "lef", "v")


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def openram_env() -> dict:
    env = dict(os.environ)
    env.update({
        "OPENRAM_ROOT": OPENRAM_ROOT,
        "OPENRAM_HOME": os.path.join(OPENRAM_ROOT, "compiler"),
        "OPENRAM_TECH": os.path.join(OPENRAM_ROOT, "technology"),
        "PDK_ROOT": PDK_ROOT,
        "PDKPATH": os.path.join(PDK_ROOT, "sky130A"),
        "PYTHONPATH": os.path.join(OPENRAM_ROOT, "compiler"),
        "PATH": "/home/rithwik/netgen-install/bin:"
                "/home/rithwik/klayout_cf/magic/bin:"
                + os.environ.get("PATH", ""),
    })
    return env


def toolchain_versions() -> dict:
    def git(*args):
        try:
            return subprocess.run(["git", "-C", OPENRAM_ROOT] + list(args),
                                  capture_output=True, text=True,
                                  timeout=60).stdout.strip()
        except Exception as exc:                       # pragma: no cover
            return "unavailable: %s" % exc

    def ver(cmd):
        try:
            p = subprocess.run(cmd, capture_output=True, text=True, timeout=60,
                               env=openram_env())
            return (p.stdout + p.stderr).strip().splitlines()[0]
        except Exception as exc:
            return "unavailable: %s" % exc

    return {
        "openram_root": OPENRAM_ROOT,
        "openram_commit": git("rev-parse", "HEAD"),
        "openram_branch": git("rev-parse", "--abbrev-ref", "HEAD"),
        "openram_describe": git("log", "-1", "--format=%H %cI"),
        # Distinguish a modified OpenRAM SOURCE tree (which Stage 5 forbids)
        # from untracked PDK-derived cell libraries the installer creates.
        "openram_tracked_files_modified": bool(
            [l for l in git("status", "--porcelain").splitlines()
             if not l.startswith("??")]),
        "openram_untracked_paths": [l[3:] for l in
                                    git("status", "--porcelain").splitlines()
                                    if l.startswith("??")],
        "pdk_root": PDK_ROOT,
        "pdk_sky130A_present": os.path.isdir(os.path.join(PDK_ROOT, "sky130A")),
        "magic": ver(["magic", "--version"]),
        "netgen": ver(["netgen", "-batch", "quit"]),
        "klayout": ver([KLAYOUT, "-v"]),
    }


# --------------------------------------------------------------------------
# Compiler invocation
# --------------------------------------------------------------------------

def write_config(name: str, word_size_bytes: int, wpr: int, data_path: str,
                 outdir: str, check_lvsdrc: bool) -> str:
    cfg_path = os.path.join(outdir, name + "_cfg.py")
    out_path = os.path.join(outdir, "out")
    os.makedirs(out_path, exist_ok=True)
    with open(cfg_path, "w") as fh:
        fh.write("""# GENERATED by model2rtl Stage 5 (src/model2rtl/openrom.py).
# words_per_row is an internal physical folding choice only: the logical depth,
# the word width and the bit packing are unchanged by it.
word_size = %d
words_per_row = %d
check_lvsdrc = %s
use_nix = False
rom_data = "%s"
data_type = "hex"
output_name = "%s"
output_path = "%s/"
tech_name = "sky130"
nominal_corner_only = True
route_supplies = "ring"
""" % (word_size_bytes, wpr, check_lvsdrc, data_path, name, out_path))
    return cfg_path


def _run(cfg_path: str, cwd: str, timeout: int) -> Tuple[int, str, float]:
    cmd = [os.path.join(OPENRAM_ROOT, ".venv", "bin", "python"),
           os.path.join(OPENRAM_ROOT, "rom_compiler.py"), "-d", cfg_path]
    t0 = time.time()
    try:
        # stdin MUST be closed: OpenRAM drops into pdb on an internal error and
        # would otherwise wait for input forever.
        p = subprocess.run(cmd, cwd=cwd, env=openram_env(),
                           stdin=subprocess.DEVNULL, capture_output=True,
                           text=True, timeout=timeout)
        return p.returncode, p.stdout + p.stderr, time.time() - t0
    except subprocess.TimeoutExpired as exc:
        return -1, "TIMEOUT after %d s\n%s" % (timeout, exc.stdout or ""), \
            time.time() - t0


def error_signature(log_text: str) -> dict:
    """The real failure, not the pdb noise OpenRAM prints afterwards."""
    lines = log_text.splitlines()
    frames = [l.strip() for l in lines
              if l.strip().startswith('File "/home/rithwik/OpenRAM')]
    errs = [l for l in lines if l.startswith("ERROR")]
    exc = [l.strip() for l in lines
           if re.match(r"^\w*(Error|Exception)\b", l.strip())
           and "BdbQuit" not in l]
    return {
        "openram_error_lines": errs[-3:],
        "last_openram_frame": frames[-1] if frames else None,
        "exception": exc[-1] if exc else None,
        "note": "OpenRAM enters pdb on internal errors, so the log tail is "
                "always BdbQuit; the frame above is the real failure point.",
    }


def parse_physical_verification(log_text: str, name: str) -> dict:
    drc = None
    m = re.search(r"DRC Errors\s+%s\s+(\d+)" % re.escape(name), log_text)
    if m:
        drc = int(m.group(1))
    elif re.search(r"DRC.*%s.*(passed|clean)" % re.escape(name), log_text, re.I):
        drc = 0
    lvs = "not run"
    if re.search(r"%s\s+LVS mismatch" % re.escape(name), log_text):
        lvs = "MISMATCH"
    elif re.search(r"LVS\s+Errors\s+%s\s+0" % re.escape(name), log_text):
        lvs = "clean"
    elif re.search(r"LVS.*(passed|clean)", log_text, re.I):
        lvs = "clean"
    return {
        "drc_errors": drc,
        "drc_status": ("clean" if drc == 0 else ("%d errors" % drc)
                       if drc is not None else "not run / not reported"),
        "lvs_status": lvs,
    }


def collect_views(outdir: str, name: str, root: str) -> Dict[str, dict]:
    od = os.path.join(outdir, "out")
    views = {}
    for ext in VIEW_EXTS:
        p = os.path.join(od, "%s.%s" % (name, ext))
        if os.path.exists(p) and os.path.getsize(p) > 0:
            views[ext] = {"path": os.path.relpath(p, root),
                          "bytes": os.path.getsize(p),
                          "sha256": sha256_file(p)}
    # anything else the tool emitted that we did not anticipate
    if os.path.isdir(od):
        for f in sorted(os.listdir(od)):
            ext = f[len(name) + 1:] if f.startswith(name + ".") else None
            if ext and ext not in views and ext not in VIEW_EXTS:
                p = os.path.join(od, f)
                views[ext] = {"path": os.path.relpath(p, root),
                              "bytes": os.path.getsize(p),
                              "sha256": sha256_file(p),
                              "unanticipated": True}
    return views


@dataclass
class RomBuild:
    name: str
    depth: int
    width: int
    outdir: str
    attempts: List[dict] = field(default_factory=list)
    words_per_row: Optional[int] = None
    returncode: Optional[int] = None
    elapsed: float = 0.0
    views: Dict[str, dict] = field(default_factory=dict)
    generated: bool = False
    data: dict = field(default_factory=dict)
    physical_verification: dict = field(default_factory=dict)
    error: dict = field(default_factory=dict)


def build_rom(name: str, depth: int, width_bits: int, hex_stream: str,
              outdir: str, root: str,
              wpr_candidates: Sequence[int] = DEFAULT_WPR_CANDIDATES,
              check_lvsdrc: bool = False, timeout: int = 10800) -> RomBuild:
    """Generate one OpenROM macro, trying documented words_per_row values.

    Every attempt -- including every failure, with its traceback frame and the
    resulting array geometry -- is recorded.  Nothing is retried silently.
    """
    if width_bits % 8:
        raise ValueError("%s: %d-bit word is not byte granular; OpenROM's "
                         "word_size is expressed in bytes" % (name, width_bits))
    os.makedirs(outdir, exist_ok=True)
    b = RomBuild(name=name, depth=depth, width=width_bits, outdir=outdir)

    data_path = os.path.join(outdir, name + ".hex")
    with open(data_path, "w") as fh:
        fh.write(hex_stream)
    read_back = open(data_path).read().strip()
    if read_back != hex_stream.strip():
        raise RuntimeError("%s: ROM data file did not round trip" % name)
    b.data = {
        "path": os.path.relpath(data_path, root),
        "sha256": sha256_file(data_path),
        "hex_digits": len(hex_stream.strip()),
        "bits": len(hex_stream.strip()) * 4,
    }

    for wpr in wpr_candidates:
        cfg = write_config(name, width_bits // 8, wpr, data_path, outdir,
                           check_lvsdrc)
        rc, log, elapsed = _run(cfg, outdir, timeout)
        logpath = os.path.join(outdir, "%s_wpr%d.log" % (name, wpr))
        with open(logpath, "w") as fh:
            fh.write(log)
        views = collect_views(outdir, name, root)
        missing = [v for v in REQUIRED_VIEWS if v not in views]
        ok = (rc == 0 and not missing)
        attempt = {
            "words_per_row": wpr,
            "array_rows": -(-depth // wpr),
            "array_cols": width_bits * wpr,
            "returncode": rc,
            "elapsed_seconds": round(elapsed, 1),
            "log": os.path.relpath(logpath, root),
            "views_generated": sorted(views),
            "missing_required_views": missing,
            "generated": ok,
        }
        if not ok:
            attempt["error_signature"] = error_signature(log)
        b.attempts.append(attempt)
        if ok:
            b.words_per_row = wpr
            b.returncode = rc
            b.elapsed = elapsed
            b.views = views
            b.generated = True
            b.physical_verification = parse_physical_verification(log, name)
            b.physical_verification["checked_during_generation"] = check_lvsdrc
            return b
        # clean the output dir so a later attempt cannot inherit stale views
        od = os.path.join(outdir, "out")
        for f in list(os.listdir(od)) if os.path.isdir(od) else []:
            if f.startswith(name + "."):
                os.remove(os.path.join(od, f))

    b.generated = False
    b.error = b.attempts[-1].get("error_signature", {}) if b.attempts else {}
    return b


# --------------------------------------------------------------------------
# Independent content verification, straight out of the generated SPICE
# --------------------------------------------------------------------------

#: Derived empirically in Stage 5 from the Stage-2 weights_l2 macro, whose
#: contents are known, and confirmed exactly on 1280/1280 bits:
#:
#:     row    = word_address // words_per_row
#:     subcol = word_address %  words_per_row
#:     col    = bit * words_per_row + subcol,  bit numbered MSB first
#:     cell   = one_cell  when  word_bit(width-1-bit) == 1
#:
#: One extra all-ones row is emitted below the data rows; it holds no data.
SPICE_BIT_MAP = ("row = addr // words_per_row; col = bit*words_per_row + "
                 "addr % words_per_row with bit numbered MSB first; "
                 "rom_base_one_cell = 1, rom_base_zero_cell = 0")

_BITCELL = re.compile(
    r"^Xbit_r(\d+)_c(\d+)\n(?:\+.*\n)*?\+\s*\S*rom_base_(one|zero)_cell\s*$",
    re.M)


def spice_bit_grid(sp_path: str, name: str) -> Dict[Tuple[int, int], int]:
    text = open(sp_path).read()
    m = re.search(r"^\.SUBCKT %s_rom_base_array.*?^\.ENDS"
                  % re.escape(name), text, re.S | re.M)
    if not m:
        raise RuntimeError("%s: no rom_base_array subcircuit in %s"
                           % (name, sp_path))
    grid = {}
    for r, c, kind in _BITCELL.findall(m.group(0)):
        grid[(int(r), int(c))] = 1 if kind == "one" else 0
    if not grid:
        raise RuntimeError("%s: no programmed bit cells found" % name)
    return grid


def verify_spice_content(sp_path: str, name: str, rows: Sequence[int],
                         width: int, words_per_row: int) -> dict:
    """Compare every programmed cell in the generated netlist against the
    physical image.  This is the proof that the GDS/SPICE macro was built from
    the same bits the logical model uses."""
    grid = spice_bit_grid(sp_path, name)
    depth = len(rows)
    n_rows = -(-depth // words_per_row)
    checked = mismatches = 0
    first_bad = []
    for a in range(depth):
        r, sub = a // words_per_row, a % words_per_row
        for bit in range(width):
            c = bit * words_per_row + sub
            want = (rows[a] >> (width - 1 - bit)) & 1
            got = grid.get((r, c))
            if got is None:
                raise RuntimeError("%s: netlist has no cell at r%d c%d"
                                   % (name, r, c))
            checked += 1
            if got != want:
                mismatches += 1
                if len(first_bad) < 5:
                    first_bad.append({"addr": a, "bit": bit, "row": r,
                                      "col": c, "expected": want, "found": got})
    extra = {k: v for k, v in grid.items() if k[0] >= n_rows}
    return {
        "spice": os.path.basename(sp_path),
        "bit_map": SPICE_BIT_MAP,
        "data_rows": n_rows,
        "cells_in_netlist": len(grid),
        "bits_checked": checked,
        "bit_mismatches": mismatches,
        "first_mismatches": first_bad,
        "non_data_cells": len(extra),
        "non_data_cells_all_ones": all(v == 1 for v in extra.values()),
        "exact": mismatches == 0,
    }


# --------------------------------------------------------------------------
# Measured area
# --------------------------------------------------------------------------

_BBOX_RB = r'''
gds = ENV["GDS_IN"]
ly = RBA::Layout.new
ly.read(gds)
c = ly.top_cells[0]
b = c.dbbox
puts "BBOX_JSON {\"top_cell\": \"#{c.name}\", \"n_top_cells\": #{ly.top_cells.size}, \"cells\": #{ly.cells}, \"dbu\": #{ly.dbu}, \"left_um\": #{b.left}, \"bottom_um\": #{b.bottom}, \"right_um\": #{b.right}, \"top_um\": #{b.top}, \"width_um\": #{b.width}, \"height_um\": #{b.height}, \"area_um2\": #{b.width * b.height}}"
'''


def gds_bbox(gds_path: str, scratch: str) -> dict:
    """Measure the macro bounding box FROM THE GDS, hierarchy resolved.

    KLayout reads the real layout database; nothing is taken from a log line.
    """
    import json
    if not os.path.isfile(KLAYOUT):
        raise RuntimeError("klayout not found at %s" % KLAYOUT)
    os.makedirs(scratch, exist_ok=True)
    rb = os.path.join(scratch, "_bbox.rb")
    with open(rb, "w") as fh:
        fh.write(_BBOX_RB)
    env = dict(os.environ, GDS_IN=os.path.abspath(gds_path))
    p = subprocess.run([KLAYOUT, "-b", "-r", rb], capture_output=True,
                       text=True, env=env, timeout=1800)
    for line in (p.stdout + p.stderr).splitlines():
        if line.startswith("BBOX_JSON "):
            d = json.loads(line[len("BBOX_JSON "):])
            d["source"] = "GDS, measured with KLayout (hierarchy resolved)"
            d["gds_sha256"] = sha256_file(gds_path)
            return d
    raise RuntimeError("klayout produced no bbox for %s:\n%s"
                       % (gds_path, p.stdout + p.stderr))


_LEF_SIZE = re.compile(r"^\s*SIZE\s+([\d.]+)\s+BY\s+([\d.]+)\s*;", re.M)


def lef_size(lef_path: str) -> Optional[dict]:
    """The LEF abstract SIZE, recorded as a cross-check only.

    It is normally SMALLER than the GDS bounding box because the GDS also
    contains the supply ring and labels outside the abstract outline.
    """
    if not os.path.isfile(lef_path):
        return None
    m = _LEF_SIZE.search(open(lef_path).read())
    if not m:
        return None
    w, h = float(m.group(1)), float(m.group(2))
    return {"width_um": w, "height_um": h, "area_um2": w * h,
            "note": "LEF abstract outline; the GDS bounding box is the "
                    "reported area and is usually larger"}


# --------------------------------------------------------------------------
# The upstream OpenROM Verilog: observed properties, never used as our backend
# --------------------------------------------------------------------------

def inspect_generated_verilog(v_path: str) -> dict:
    text = open(v_path).read()
    return {
        "path": v_path,
        "bytes": len(text),
        "uses_readmemb": "$readmemb" in text,
        "uses_readmemh": "$readmemh" in text,
        "has_delays": bool(re.search(r"#\s*\d", text)),
        "has_negedge": "negedge" in text,
        "byte_oriented_interface": bool(re.search(r"\[\s*7\s*:\s*0\s*\]", text)),
        "module_names": re.findall(r"^\s*module\s+(\w+)", text, re.M),
        "port_lines": [l.strip() for l in text.splitlines()
                       if re.match(r"\s*(input|output|inout)\b", l)],
        "verdict": ("upstream artefact only: it is NOT used as the model2rtl "
                    "functional backend"),
    }
